add localai api

diff --git a/s-pilot b/s-pilot
--- a/s-pilot
+++ b/s-pilot
@@ -35,10 +35,22 @@ if [[ "$USE_API" == "ollama" ]]; then
 	fi
 fi
 
+# check if the OLLAMA host is set
+if [[ "$USE_API" == "localai" ]]; then
+	if [[ -z "$LOCALAI_SERVER_IP" ]]; then
+		echo "Error: LOCALAI_SERVER_IP is not set in the configuration file."
+		exit 1
+	fi
+	if ! [[ $LOCALAI_SERVER_IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+		echo "Error: LOCALAI_SERVER_IP is not a valid IP address."
+		exit 1
+	fi
+fi
+
 usage() {
 	cat <<EOF
 A simple, lightweight shell script to use OpenAI's Language Models and DALL-E 
-or Ollama models or MistralAI models from the terminal without installing Python or Node.js.
+or Ollama models or MistralAI models or LocalAI from the terminal without installing Python or Node.js.
 Open Source and written in 100% Shell (Bash).
 
 https://github.com/reid41/shell-pilot.git
@@ -62,7 +74,7 @@ Commands:
   cmd: - To get a command with the specified functionality and run it, just type "cmd:" and explain what you want to achieve. The script will always ask you if you want to execute the command.
 
 Options:
-  cmp, -cmp, --change-model-provider   Change the model provider between openai, ollama, mistralai
+  cmp, -cmp, --change-model-provider   Change the model provider between openai, ollama, mistralai, localai
 
   e, -e, --edit                        Edit the configuration file directly
 
@@ -151,9 +163,10 @@ show_llm_models_output(){
 		cat "$LIST_MODELS_CACHE_FILE"
 	elif [[ "$USE_API" == "mistralai" ]]; then
 		cat "$LIST_MODELS_CACHE_FILE"
+	elif [[ "$USE_API" == "localai" ]]; then
+		cat "$LIST_MODELS_CACHE_FILE"
 	fi
 }
-
 
 # list the models
 list_models() {
@@ -189,6 +202,9 @@ list_models() {
                 mistralai)
                     grep -qi "mistral" "$cache_file" && content_valid=true
                     ;;
+              localai)
+                    grep -qi "stablediffusion" "$cache_file" && content_valid=true
+                    ;;
             esac
 
             if [[ "$content_valid" == true ]]; then
@@ -221,6 +237,9 @@ fetch_and_cache_models() {
 		models_response=$(fetch_model_from_openai)
         handle_error "$models_response"
         echo $models_response | jq -r -C '.data[] | {id, owned_by, created}' > "$cache_file"
+    elif [[ "$USE_API" == "localai" ]]; then
+		models_response=$(fetch_model_from_localai)
+        echo $models_response | jq -r -C '.data[] | {id, object}' > "$cache_file"
 	elif [[ "$USE_API" == "mistralai" ]]; then
 		models_response=$(fetch_model_from_mistralai)
 	 	echo $models_response | jq -r -C '.data[] | {id, owned_by, created}'  > "$cache_file"
@@ -267,7 +286,6 @@ build_chat_context() {
 	fi
 }
 
-# format
 escape() {
 	echo "$1" | jq -Rrs 'tojson[1:-1]'
 }
@@ -367,7 +385,6 @@ update_config() {
     fi
 }
 
-# check the common settings
 check_the_setting(){
 	local setting_name="$1"
 	local setting_variable="$2"
@@ -472,6 +489,8 @@ code_chat_function(){
 			if [[ "$USE_API" == "ollama" ]]; then
 				response_data=$(echo $response | jq -r '.message.content')
 			elif [[ "$USE_API" == "openai" ]]; then
+				response_data=$(echo $response | jq -r '.choices[].message.content')
+			elif [[ "$USE_API" == "localai" ]]; then
 				response_data=$(echo $response | jq -r '.choices[].message.content')
 			elif [[ "$USE_API" == "mistralai" ]]; then
 				response_data=$(echo $response | jq -r '.choices[].message.content')
@@ -691,6 +710,9 @@ while [[ "$#" -gt 0 ]]; do
 		if [[ "$USE_API" == "openai" ]]; then
 			update_config "$2" "MODEL_OPENAI"
 			check_the_setting "openai model" "MODEL_OPENAI"
+		elif [[ "$USE_API" == "localai" ]]; then
+			update_config "$2" "MODEL_LOCALAI"
+			check_the_setting "localai model" "MODEL_LOCALAI"
 		elif [[ "$USE_API" == "mistralai" ]]; then
 			update_config "$2" "MODEL_MISTRALAI"
 			check_the_setting "mistralai model" "MODEL_MISTRALAI"
@@ -716,7 +738,7 @@ while [[ "$#" -gt 0 ]]; do
 	cmp | -cmp | --change-model-provider)
 		validate_not_empty "$2"
 		# check if the model provider is valid
-		if [[ "$2" == "openai" || "$2" == "ollama" || "$2" == "mistralai" ]]; then
+		if [[ "$2" == "openai" || "$2" == "ollama" || "$2" == "mistralai" || "$2" == "localai" ]]; then
 			# update the model provider
 			update_config "$2" "USE_API"
 			# clean the cache
@@ -828,6 +850,15 @@ while $running; do
 			wait $dynamic_spinner_pid
 			echo -e "$OVERWRITE_PROCESSING_LINE"
 			echo -e "${SHELLPILOT_CYAN_LABEL}Complete details for model: ${prompt#*model:}\n ${model_data}"
+		elif [[ "$USE_API" == "localai" ]]; then
+			models_response=$(fetch_model_from_localai)
+			model_data=$(echo $models_response | jq -r -C '.data[] | select(.id=="'"${prompt#*model:}"'")')
+			# stop the spinner
+			cat ${SPINNER_SIGNAL_FILE} >/dev/null 2>&1
+			echo "1" > ${SPINNER_SIGNAL_FILE}
+			wait $dynamic_spinner_pid
+			echo -e "$OVERWRITE_PROCESSING_LINE"
+			echo -e "${SHELLPILOT_CYAN_LABEL}Complete details for model: ${prompt#*model:}\n ${model_data}"
 		elif [[ "$USE_API" == "mistralai" ]]; then
 			models_response=$(fetch_model_from_mistralai)
 			model_data=$(echo $models_response | jq -r -C '.data[] | select(.id=="'"${prompt#*model:}"'")')
@@ -885,6 +916,8 @@ while $running; do
 		if [[ "$USE_API" == "ollama" ]]; then
 			response_data=$(echo $response | jq -r '.message.content')
 		elif [[ "$USE_API" == "openai" ]]; then
+			response_data=$(echo $response | jq -r '.choices[].message.content')
+		elif [[ "$USE_API" == "localai" ]]; then
 			response_data=$(echo $response | jq -r '.choices[].message.content')
 		elif [[ "$USE_API" == "mistralai" ]]; then
 			response_data=$(echo $response | jq -r '.choices[].message.content')
@@ -952,6 +985,8 @@ while $running; do
 		if [[ "$USE_API" == "ollama" ]]; then
 			response_data=$(echo $response | jq -r '.message.content')
 		elif [[ "$USE_API" == "openai" ]]; then
+			response_data=$(echo $response | jq -r '.choices[].message.content')
+		elif [[ "$USE_API" == "localai" ]]; then
 			response_data=$(echo $response | jq -r '.choices[].message.content')
 		elif [[ "$USE_API" == "mistralai" ]]; then
 			response_data=$(echo $response | jq -r '.choices[].message.content')
