add moonshot

diff --git a/s-pilot b/s-pilot
--- a/s-pilot
+++ b/s-pilot
@@ -37,6 +37,13 @@ if [[ -z "$ANTHROPIC_API_KEY" && "$USE_API" == "athropic" ]]; then
 	exit 1
 fi
 
+# check if the MOONSHOT_API_KEY is set
+if [[ -z "$MOONSHOT_API_KEY" && "$USE_API" == "moonshot" ]]; then
+	echo "You need to set your MOONSHOT_API_KEY to use this script!"
+	echo "You can set it temporarily by running this on your terminal: export MOONSHOT_API_KEY=YOUR_KEY_HERE"
+	exit 1
+fi
+
 # check if the OLLAMA host is set
 if [[ "$USE_API" == "ollama" ]]; then
 	if [[ -z "$OLLAMA_SERVER_IP" ]]; then
@@ -77,6 +84,7 @@ MistralAI: "mistral-small" model.
 LocalAI: "gpt-4" model.
 ZhipuAI: "glm-4" model.
 Anthropic: "claude-3-opus-20240229" model.
+Moonshot: "moonshot-v1-8k" model.
 
 It will enter "chat" mode without any options, here are some commands you can use:
 
@@ -88,7 +96,7 @@ Commands:
 
 Options:
   cmp, -cmp, --change-model-provider   Change the model provider between openai, 
-                                       ollama, mistralai, localai, zhipuai, anthropic
+                                       ollama, mistralai, localai, zhipuai, anthropic, moonshot
 
   e, -e, --edit                        Edit the configuration file directly
 
@@ -516,6 +524,8 @@ code_chat_function(){
 				response_data=$(echo $response | jq -r '.choices[].message.content')
 			elif [[ "$USE_API" == "anthropic" ]]; then
 				response_data=$(echo $response | jq -r '.content[0].text')
+			elif [[ "$USE_API" == "moonshot" ]]; then
+				response_data=$(echo $response | jq -r '.choices[].message.content')
 			fi
 			add_assistant_response_to_chat_message "$(escape "$response_data")"
 			# execute_cmd=$(echo "$response_data" | sed 's/[`$]//g')
@@ -747,6 +757,9 @@ while [[ "$#" -gt 0 ]]; do
 		elif [[ "$USE_API" == "anthropic" ]]; then
 			update_config "$2" "MODEL_ANTHROPIC"
 			check_the_setting "anthropic model" "MODEL_ANTHROPIC"
+		elif [[ "$USE_API" == "moonshot" ]]; then
+			update_config "$2" "MODEL_MOONSHOT"
+			check_the_setting "moonshot model" "MODEL_MOONSHOT"
 		fi
 		;;
 	mlp | -mlp | --multi-line-prompt)
@@ -766,7 +779,7 @@ while [[ "$#" -gt 0 ]]; do
 	cmp | -cmp | --change-model-provider)
 		validate_not_empty "$2"
 		# check if the model provider is valid
-		if [[ "$2" == "openai" || "$2" == "ollama" || "$2" == "mistralai" || "$2" == "localai"   || "$2" == "zhipuai" || "$2" == "anthropic" ]]; then
+		if [[ "$2" == "openai" || "$2" == "ollama" || "$2" == "mistralai" || "$2" == "localai"   || "$2" == "zhipuai" || "$2" == "anthropic" || "$2" == "moonshot" ]]; then
 			# update the model provider
 			update_config "$2" "USE_API"
 			# clean the cache
@@ -774,7 +787,7 @@ while [[ "$#" -gt 0 ]]; do
 			check_the_setting "model provider" "USE_API"
 		else
 			# print error message and exit if the model provider is invalid
-			echo -e "Error: Invalid model provider. Please choose \033[1;36mopenai\033[0m or \033[1;37mmistralai\033[0m or \033[1;35mollama\033[0m or \033[1;35mlocalai\033[0m or \033[1;35mzhipuai\033[0m or \033[1;35manthropic\033[0m."
+			echo -e "Error: Invalid model provider. Please choose \033[1;36mopenai\033[0m or \033[1;37mmistralai\033[0m or \033[1;35mollama\033[0m or \033[1;35mlocalai\033[0m or \033[1;35mzhipuai\033[0m or \033[1;35manthropic\033[0m or \033[1;35mmoonshot\033[0m."
 			[[ "${BASH_SOURCE[0]}" != "$0" ]] && return 1 || exit 1
 		fi
 		;;
@@ -945,6 +958,8 @@ while $running; do
 			response_data=$(echo $response | jq -r '.message.content')
 		elif [[ "$USE_API" == "openai" ]]; then
 			response_data=$(echo $response | jq -r '.choices[].message.content')
+		elif [[ "$USE_API" == "moonshot" ]]; then
+			response_data=$(echo $response | jq -r '.choices[].message.content')
 		elif [[ "$USE_API" == "localai" ]]; then
 			response_data=$(echo $response | jq -r '.choices[].message.content')
 		elif [[ "$USE_API" == "mistralai" ]]; then
@@ -1017,6 +1032,8 @@ while $running; do
 		if [[ "$USE_API" == "ollama" ]]; then
 			response_data=$(echo $response | jq -r '.message.content')
 		elif [[ "$USE_API" == "openai" ]]; then
+			response_data=$(echo $response | jq -r '.choices[].message.content')
+		elif [[ "$USE_API" == "moonshot" ]]; then
 			response_data=$(echo $response | jq -r '.choices[].message.content')
 		elif [[ "$USE_API" == "localai" ]]; then
 			response_data=$(echo $response | jq -r '.choices[].message.content')
